### ISSUE TITLE
Batch file simplifications

### ISSUE THREAD

**Issue by konrad-schwarz** [fatso83/vmware-auto-suspend#10]
The following simplification is possible to `SuspendRunningVMs.bat`:

When creating `%temp%\vmlist.txt`, the pipe segment with the `FIND /V` can be eliminated, replacing it with a `"skip=1 delims=*"` in the `FOR /F` statement (which skips the first line, which contains the `Total Running VMs: ` string.  (https://github.com/fatso83/vmware-auto-suspend/issues/6 also uses this technique.) Should `:ResumeVM` be called from a `FOR /F` loop, the same applies.

Also, the blank line at the end of the output of `vmrun list` is produced by `cmd.exe`, not by `vmrun list` itself, so if this blank line is the only reason for the blank line checks in `:SuspendVM` and `:ResumeVM`, those checks can be removed.

**Comment by fatso83** [comment]
OK, thanks! Feel free to supply a PR if you have tested the results to work :)
