### ISSUE TITLE
Specify specific VMs to Suspend and Shut Down others.

### ISSUE THREAD

**Issue by siw1973** [fatso83/vmware-auto-suspend#12]
I'm using the script to suspend all my VMs cleanly in case of a Windows Update Reboot, however when doing this with a Ubuntu Desktop and Home Assistant VM they do not suspend correctly. Windows VMs work perfectly.

Is there any way that the bat file can be modified to Shut Down specific VMs and continue to Suspend others ?

**Comment by fatso83** [comment]
Probably, but I don't have access to Windows anymore after switching jobs ....

**Comment by fatso83** [comment]
The easiest thing is to edit the BAT file and filter out on some specific string, I would assume. I believe the command to filter text is called "find" in CMD shell, akin to grep on UNIX land. Shouldn't be too hard.

**Comment by siw1973** [comment]
Thanks, I'll have a dig around, but this is way beyond my skill set !

**Comment by fatso83** [comment]
OK, took some minutes to browse around for you, and I think you should be able to get what you want by just hardcoding some simple commands. I cannot test it out for you, but you can probably adjust to your setting. So I found [this guide from Vmware](https://www.vmware.com/pdf/vix162_vmrun_command.pdf) on the `vmrun` command that [I use in the CMD script](https://github.com/fatso83/vmware-auto-suspend/blame/master/SuspendRunningVMs.bat). That guide shows that the syntax for stopping a VM is just `vmrun stop path/to/the/vm-you-want.vmx`. Obviously, "path/to/the/vm-you-want.vmx" is something you need to figure out yourself, like `D:\VmWare\Ubuntu\my.vmx`. You can list all the running vms using `vmrun list`, which should print the paths. That is exactly what the script is doing actually: listing out the vms, then executing `vmrun suspend <path-to-vmx>` for each vm from that command.


If you take a look at the current script, we [start listing out the vm's at line 13](https://github.com/fatso83/vmware-auto-suspend/blob/4f04cab5c4b9a06137b51f1870427d4c3232c630/SuspendRunningVMs.bat#L13). If you just insert a couple of lines before this where you stop the troublesome Ubuntu VM it should be good!

So the section would end up looking something like this:

```
...
SETLOCAL
REM Specify where vmrun.exe can be located
SET WSPath="C:\Program Files (x86)\VMware\VMware Workstation"


REM #### This is where your changes START
%WSPath%\vmrun.exe stop D:\VirtualMachines\Ubuntu\foo.vmx
%WSPath%\vmrun.exe stop D:\VirtualMachines\HomeAssistant\bar.vmx

REM a little 5 sec timeout to allow for the vms to stop, before continuing
timeout /t 5/nobreak
REM #### This is where your changes END


REM Get the list of currently running VMs
%WSPath%\vmrun.exe list > %temp%\vmlist.txt
...
```

I hope that should be clear. You can manually execute the script from wherever you put it, which [according to the current install script](https://github.com/fatso83/vmware-auto-suspend/blob/master/install.bat#L12) is in the folder "C:\vmware-auto-suspend". So just 
1. Right click and edit the bat file as above
2. open a Command Prompt (Win-R, type "cmd", Enter)
3. Go to the folder in the terminal: `cd C:\vmware-auto-suspend`
4. Run the script: `SuspendRunningVMs`
5. Check if everything worked fine, if not, edit the file and go to step 4, else you are finished :)

**Comment by siw1973** [comment]
This is amazingly helpful, hopefully have time to set up during the weekend.

THANKS !
