### ISSUE TITLE
The task XML is malformed.

### ISSUE THREAD

**Issue by beyefendi** [fatso83/vmware-auto-suspend#5]
PS C:\> schtasks /create /TN "Auto Suspend VMWare instances" /XML vmware-auto-suspend.xml
ERROR: The task XML is malformed.
(1,2)::ERROR: incorrect document syntax

**Comment by dmtch** [comment]
You need to convert it to utf16 (le) encoding.

**Comment by fatso83** [comment]
I am assuming this was fixed by proper encoding. Closing.

**Comment by fatso83** [comment]
Cool to see two users beside myself, btw 👯

**Comment by fatso83** [comment]
Fixed this using an install script to avoid the issue :)
https://github.com/fatso83/vmware-auto-suspend#installing
