### ISSUE TITLE
XML malformed

### ISSUE THREAD

**Issue by ltemimi** [fatso83/vmware-auto-suspend#9]
Hi I get an  error

I copied the xml content from master and I still get the issue ERROR The task XML is malformed

Please help

**Comment by ltemimi** [comment]
SUCCESS
Save  as ANSI is crucial it now works thanks

**Comment by fatso83** [comment]
@ltemimi Did you follow the instructions to _download_ the raw file? **Copy-pasting it as you seem to imply will cause those issues.** 

Do you think I could improve the instructions?

**Comment by ltemimi** [comment]
Hi

Yes I did copy and paste , the instructions are OK just specify the file needs to be saved as Ansi.
Thanks for your help

**Comment by fatso83** [comment]
I think I will just change it to download the repo as a zip, to avoid all issues :)

**Comment by fatso83** [comment]
Fixed. I added a super minimal install section which just involved downloading the zip and clicking `install.bat.`

**Comment by ltemimi** [comment]
Great thanks
